"""Add status and email_verified_at to User, make phone_number nullable

Revision ID: 065ffed99cfc
Revises: e474473ec470
Create Date: 2025-07-19 11:05:59.976603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065ffed99cfc'
down_revision = 'e474473ec470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    op.execute("UPDATE users SET status = 'active' WHERE status IS NULL")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               nullable=False)
    # ### end Alembic commands ###
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('email_verified_at')

    # ### end Alembic commands ###
