"""Enhance permissions and add usage tracking

Revision ID: 544689ef5d46
Revises: e2d085d50f0c
Create Date: 2025-07-22 10:42:06.319304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544689ef5d46'
down_revision = 'e2d085d50f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_identifier', sa.String(length=255), nullable=True),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_identifier', 'feature', 'usage_date', name='_guest_feature_date_uc'),
    sa.UniqueConstraint('user_id', 'feature', 'usage_date', name='_user_feature_date_uc')
    )
    with op.batch_alter_table('user_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_usage_logs_feature'), ['feature'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_usage_logs_guest_identifier'), ['guest_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_usage_logs_usage_date'), ['usage_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_usage_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission_type', sa.String(length=50), server_default='user', nullable=False))
        batch_op.create_index(batch_op.f('ix_permissions_permission_type'), ['permission_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_permission_type'))
        batch_op.drop_column('permission_type')

    with op.batch_alter_table('user_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_usage_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_usage_logs_usage_date'))
        batch_op.drop_index(batch_op.f('ix_user_usage_logs_guest_identifier'))
        batch_op.drop_index(batch_op.f('ix_user_usage_logs_feature'))

    op.drop_table('user_usage_logs')
    # ### end Alembic commands ###
