"""Add workplace column to User model

Revision ID: e474473ec470
Revises: 2dfbbc431a3f
Create Date: 2025-07-16 17:40:59.987590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e474473ec470'
down_revision = '2dfbbc431a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workplace', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('workplace')

    # ### end Alembic commands ###
